Fix HttpConnectorTest missing symbol error
`HttpConnectorTest` failed with the following missing symbol error after
cherry-picking commit 59cf396d7d1a1a35c01a99bcaae742d76d872c5b:

```txt
src/test/java/com/google/devtools/build/lib/bazel/repository/downloader/HttpConnectorTest.java:378:
  error: cannot find symbol
    assertThat(ste).isPresent();
                   ^
  symbol:   method isPresent()
  location: class Subject
Target //src/test/java/com/google/devtools/build/lib/bazel/repository/downloader:DownloaderTestSuite
  failed to build
```

The easy work around was to change the expression to an equivalent
assertion, rather than trying to upgrade the Truth assertion library.