Update gtest.BUILD prior to strip_prefix
Before when `strip_prefix` is introduced, the snippet of gtest.BUILD has a glitch.
`bazel build @gtest//:main` has error with below message
```
external/gtest/googletest-release-1.7.0/src/gtest-test-part.cc:42:10: fatal error: 'src/gtest-internal-inl.h' file not found
#include "src/gtest-internal-inl.h"
```

The 1-liner PR enables `bazel build @gtest//:main`. Verified on bazel 2.0.0

Closes #10675.

PiperOrigin-RevId: 296422395