Allow negating --remote_grpc_log
Previously setting this to an empty string with `--remote_grpc_log=`
would result in it assuming it should be using the current directory as
the output path, and erroring with:

```
ERROR: /tmp/repro (Is a directory)
ERROR: Error initializing RemoteModule
```

Closes #26775.

PiperOrigin-RevId: 797229588
Change-Id: Ib187a70e5e6cf184e0e4f138d439d036100ac46f