Rollback of commit d8eec343d238129ce8b5146c4177d207a6b3683b.
*** Reason for rollback ***

These tests break on Mac: http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/561/console
E.g.: 
ERROR: /Users/ci/workspace/bazel-tests/BAZEL_VERSION/HEAD/PLATFORM_NAME/darwin-x86_64/src/java_tools/junitrunner/javatests/com/google/testing/junit/runner/BUILD:64:1: Couldn't build file src/java_tools/junitrunner/javatests/com/google/testing/junit/runner/junit4_testbridge_integration_test.runfiles/MANIFEST: Creating runfiles tree bazel-out/local-fastbuild/bin/src/java_tools/junitrunner/javatests/com/google/testing/junit/runner/junit4_testbridge_integration_test.runfiles failed: build-runfiles failed: error executing command 
  (cd /private/var/tmp/_bazel_ci/663aef0b024d9552f81e09f650e1ea55/execroot/darwin-x86_64 && \
  exec env - \
    PATH=/Users/ci/workspace/bazel-tests/BAZEL_VERSION/HEAD/PLATFORM_NAME/darwin-x86_64/.bin:/usr/bin:/bin:/usr/sbin:/sbin \
    TMPDIR=/var/folders/3[]pdj48r577v5qqr3dqn58xq40000gn/T/ \
  /private/var/tmp/_bazel_ci/663aef0b024d9552f81e09f650e1ea55/execroot/darwin-x86_64/_bin/build-runfiles bazel-out/local-fastbuild/bin/src/java_tools/junitrunner/javatests/com/google/testing/junit/runner/junit4_testbridge_integration_test.runfiles_manifest bazel-out/local-fastbuild/bin/src/java_tools/junitrunner/javatests/com/google/testing/junit/runner/junit4_testbridge_integration_test.runfiles)

*** Original change description ***

Open source the integration tests for BazelTestRunner and delete the internal versions.

--
PiperOrigin-RevId: 147587929
MOS_MIGRATED_REVID=147587929