Send Aapt2Exception message to the logger.
Currently, if there are non-suppressed errors during aapt2 processing, Bazel does not print them.

This helps with debugging https://github.com/bazelbuild/bazel/pull/5222

With this, I get:

```
ERROR: /usr/local/google/home/jingwen/code/android_scratch_project/examples/android/java/bazel/BUILD:16:1: Processing Android resources for //examples/android/java/bazel:hello_world failed (Exit 1)
May 21, 2018 5:31:01 PM com.google.devtools.build.android.ResourceProcessorBusyBox main
SEVERE: java.io.IOException: Is a directory
Target //examples/android/java/bazel:hello_world failed to build
```

instead of just:

```
ERROR: /usr/local/google/home/jingwen/code/android_scratch_project/examples/android/java/bazel/BUILD:16:1: Processing Android resources for //examples/android/java/bazel:hello_world failed (Exit 1)
Target //examples/android/java/bazel:hello_world failed to build
```

RELNOTES: None.
PiperOrigin-RevId: 197493881