Increase StackShadowPages to 20 for Starlark tests.
Avoid the following breakage on macOS:
```
intx StackShadowPages=16 is outside the allowed range [ 20 ... 50 ]
Improperly specified VM option 'StackShadowPages=16'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Broken by https://github.com/bazelbuild/bazel/commit/b6a6f1d2235175f793d5e6b7e12434af037aec28

PiperOrigin-RevId: 964100484
Change-Id: Ied9d6f37acf63da488b355f1b6524f90ca4b567f