Automated rollback of commit c9f9b0b84c4863b5b19220679e610efa17e972f0.
*** Reason for rollback ***

Some tools rely on the old message and I will first try to update them.

*** Original change description ***

Fix spitting out multiple "Build completed" messages.

Also make these a proper event, so that `--ui_event_filters` is applied
properly.

Fixes https://github.com/bazelbuild/bazel/issues/16085

RELNOTES[INC]:
This has the side effect of changing the message on unsuccessful builds from
```
FAILED: Build did NOT complete successfully (0 packages loaded)
```
to
```
ERROR: Build did NOT complete successfully
```
PiperOrigin-RevId: 484274963
Change-Id: I2a3a954510ccf5d0c973d63d3a570b7356c7a7d6