Explicitly cast ByteBuffer in clear() call to Buffer.
This works around the following error:
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at com.google.devtools.build.lib.profiler.Profiler$BinaryFormatWriter.run(Profiler.java:949)
	at java.lang.Thread.run(Thread.java:748)

JDK 9 introduced an overloaded methods with covariant return type.

Closes #5886.

PiperOrigin-RevId: 208642556