Allow a bootstrap build of Bazel on OpenBSD to succeed.
Tested on OpenBSD 6.6-current (amd64 architecture), as follows:

    # Create a 'dist' tarball. Here, `bbazel` is a binary left over from the
    # porting work leading up to this patch.
    cd ~/git/aldersondrive_bazel
    /home/me/bin/bbazel build --host_javabase=@local_jdk//:jdk :bazel-distfile

    # Perform a bootstrap build based on the tarball.
    rm -rf ~/test_bootstrap
    mkdir ~/test_bootstrap
    cd ~/test_bootstrap
    unzip ~/git/aldersondrive_bazel/bazel-bin/bazel-distfile.zip
    EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" JAVA_HOME="/usr/local/jdk-1.8.0" BAZEL_JAVAC_OPTS="-J-Xmx2g -J-Xms200m" bash ./compile.sh

The resulting Bazel binary appeared to work in some simple testing involving cc_library, cc_binary, java_library, and java_binary.

Known issues/limitations:

- For the above to work, I had to add `python` to my PATH. (On OpenBSD, the Python binary is called `python3`.)

    ln -s /usr/local/bin/python3 ~/bin/python

- Buliding a java_binary's deploy JAR fails because the `singlejar` tool fails to build. I intend to look into this issue next.

    In file included from external/remote_java_tools_linux/java_tools/src/tools/singlejar/input_jar.cc:15:
    In file included from bazel-out/host/bin/external/remote_java_tools_linux/_virtual_includes/input_jar/src/tools/singlejar/input_jar.h:27:
    bazel-out/host/bin/external/remote_java_tools_linux/_virtual_includes/diag/src/tools/singlejar/diag.h:54:2: error: Unknown platform
    #error Unknown platform
     ^

- Running Bazel requires a `--host_javabase=@local_jdk//:jdk` flag.

- Sandboxing is unsupported.