Set language version in bazel_coverage_java_test
On Ubuntu 20.04, we see:

```txt
JAVA_HOME=(/usr/lib/jvm/java-21-openjdk-amd64)
```

This leads to this test failing with:

```txt
Error occurred during initialization of VM
java.lang.Error: Could not create SecurityManager
  at java.lang.System.initPhase3(java.base@11.0.15/System.java:2065)
Caused by: java.lang.ClassNotFoundException: allow
  at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@11.0.15/BuiltinClassLoader.java:581)
  at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@11.0.15/ClassLoaders.java:178)
  at java.lang.ClassLoader.loadClass(java.base@11.0.15/ClassLoader.java:522)
  at java.lang.Class.forName0(java.base@11.0.15/Native Method)
  at java.lang.Class.forName(java.base@11.0.15/Class.java:398)
  at java.lang.System.initPhase3(java.base@11.0.15/System.java:2050)
```

Based on the hint from the following comment, setting
`--java_language_version` and `--tool_java_language_version` may help:

- https://github.com/bazelbuild/bazel/issues/14502#issuecomment-1020950439