Allow negating --remote_grpc_log
Previously setting this to an empty string with `--remote_grpc_log=`
would result in it assuming it should be using the current directory as
the output path, and erroring with:

```
ERROR: /tmp/repro (Is a directory)
ERROR: Error initializing RemoteModule
```