Revert "Use digest function matching the checksum in gRPC remote downloader"
This reverts commit ef45e02bfb4af1124bb9ad1ef94f36c70c82ce48.

The change causes failure for workspaces with BLAKE3 enabled while the
repository rules use SHA256.  The remote asset request/response will be
sent with SHA256 while Bazel would attempt to verify the digest with
BLAKE3 and thus, causes errors like this

```
ERROR: /root/workspace/output-base/external/bazel_tools/tools/build_defs/repo/http.bzl:137:45: An error occurred during the fetch of repository 'rules_cc+':
   Traceback (most recent call last):
        File "/root/workspace/output-base/external/bazel_tools/tools/build_defs/repo/http.bzl", line 137, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: com.google.devtools.build.lib.remote.common.CacheNotFoundException: Missing digest: abc605dd850f813bb37004b77db20106a19311a96b2da1c92b789da529d28fe1/178823
```

It seems like the original reported issue on Slack was caused by Remote
Asset Server implemenation did not support digest functions that is
different from the one used in the qualifier.  Such issue should be
fixed in the server implemenation instead of Bazel.