Try disabling grpc server auto flow control
Was turned on by default during 1.26.0->1.31.1 grpc-java bump
It seems that it may be causing errors in RBE:

io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Bandwidth exhausted
HTTP/2 error code: ENHANCE_YOUR_CALM
Received Goaway
too_many_pings

https://github.com/bazelbuild/bazel/issues/12264
https://github.com/grpc/grpc-java/pull/7302