Fix duplicated error message on explicit incompatible target
Currently the "cannot be built, but was explicitly requested" error
message gets printed twice. This can be seen when running on the
integration tests:

    $ bazel test -c opt //src/test/shell/integration:target_compatible_with_test --test_output=streamed --test_filter=test_aquery_incompatible_target
    ** test_aquery_incompatible_target *********************************************
    -- Test log: -----------------------------------------------------------
    $TEST_TMPDIR defined: output root default is '/bazel-cache/phil/bazel/_bazel_phil/9ea7728127d38e06511786263f870905/sandbox/linux-sandbox/3035/execroot/io_bazel/_tmp/c749fd38ac9a4ad6bd41e9653bbceab5' and max_idle_secs default is '15'.
    WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
    /etc/bazel.bazelrc
    Extracting Bazel installation...
    Starting local Bazel server and connecting to it...
    Loading:
    Loading: 0 packages loaded
    Analyzing: target //target_skipping:sh_foo1 (1 packages loaded, 0 targets configured)
    Analyzing: target //target_skipping:sh_foo1 (33 packages loaded, 134 targets configured)
    ERROR: Target //target_skipping:sh_foo1 is incompatible and cannot be built, but was explicitly requested.
    Dependency chain:
        //target_skipping:sh_foo1 (e1f684)
        //target_skipping:foo1.sh (e1f684)
        //target_skipping:genrule_foo1 (e1f684)   <-- target platform (//target_skipping:foo3_platform) didn't satisfy constraint //target_skipping:foo1: Target //target_skipping:sh_foo1 is incompatible and cannot be built, but was explicitly requested.
    Dependency chain:
        //target_skipping:sh_foo1 (e1f684)
        //target_skipping:foo1.sh (e1f684)
        //target_skipping:genrule_foo1 (e1f684)   <-- target platform (//target_skipping:foo3_platform) didn't satisfy constraint //target_skipping:foo1
    INFO: Elapsed time: 5.525s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully (36 packages loaded, 159 targets configured)
    FAILED: Build did NOT complete successfully (36 packages loaded, 159 targets configured)

This patch fixes the issue by dropping the `cause` parameter in the
`ViewCreationFailedException` constructor. I'm not sure of the
intended use case, but I suspect the `cause` parameter is used when
the message is different from the cause. Since in this case the error
message is directly taken from the cause, there's no need to specify
`cause`.

Fixes #15427