Move `--null` query option to `CommonQueryOptions` to support `cquery` and `aquery`.
The underlying `--line_terminator_null` option is defined on `CommonQueryOptions`, but its expansion flag `--null` was only defined on `QueryOptions`. Consequently, passing `--null` to `cquery` or `aquery` failed:

Before:
```
$ blaze cquery --null //pkg:target
ERROR: --null :: Unrecognized option: --null
```

After:
```
$ blaze cquery --null //pkg:target
//pkg:target (null)\0
```

Moving `--null` to `CommonQueryOptions` allows `cquery` and `aquery` to use the flag consistently with `query`.

Closes #28982.

PiperOrigin-RevId: 992364284
Change-Id: I09b53c8ae315cd318a36f7b74998d05cdbe805da