Add patch to revert b8bbe92f8 in abseil-cpp project
This is needed to fix this breakage in grpc in Windows:

external/com_github_grpc_grpc/src/core/lib/gprpp/status_helper.cc(234):
error C2338: absl::Time needs to be able to be memcopied