bazel analysis: don't report fake stack frames
Prior to this change, Blaze's analysis added a fake stack frame
whenever analysis failed. The fake frame had the location of
the rule instantiation and the name "myrule(name = 'r')".
This information is redundant with the standard information
supplied by ruleContext.ruleError, and it's misleading to the
reader (and profiler) because it's not the actual control flow.

Aspect errors are changed in the analogous manner.

Example:

== test/inc.bzl ==
def g():
  1 // 0

def _f_impl(ctx):
   g()

f = rule(implementation = _f_impl)

== stderr ==
ERROR: test/BUILD:2:2: in f rule //test:f:
Traceback (most recent call last):
	File "test/BUILD", line 2, column 2, in f(name = 'f')   \   these two lines
		f(name ='f')                                    /   are now omitted
	File "test/inc.bzl", line 5, column 5, in _f_impl
		g()
	File "test/inc.bzl", line 2, column 5, in g
		1 // 0
Error: integer division by zero
ERROR: Analysis of target '//test:f' failed; build aborted: Analysis of target '//test:f' failed
PiperOrigin-RevId: 328541590