Android font resource support
Fixes #4381

Without layoutlib 26+, this test is expected to fail with:

```
ERROR: /private/var/tmp/_bazel_jin/ed227ac31d5e65f9c3effb1d1fe2605e/sandbox/4960637019899260266/execroot/io_bazel/_tmp/845372d54b28cdaedc66e35385e5009a/workspace.u0NdZr9w/java/bazel/BUILD:14:22: in resource_files attribute of android_binary rule //java/bazel:bin: 'java/bazel/res/font/Roboto.ttf' is not in the expected resource directory structure of <resource directory>/{anim,animator,color,drawable,interpolator,layout,menu,mipmap,raw,transition,values,xml}/<file>
ERROR: Analysis of target '//java/bazel:bin' failed; build aborted: Analysis of target '//java/bazel:bin' failed; build aborted
INFO: Elapsed time: 26.248s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (36 packages loaded)
```

We will first need to upgrade the layoutlib jar in `//third_party/android_common` to 26+, rebase, then merge this set of tests.

Closes #5287.

Change-Id: Icad80e7e40df4ff6d2fc3373d37cfd9972e8d400
PiperOrigin-RevId: 198893525