Add configurable hard and soft size limits for .bzl and .scl files.
Enforces hard (`--max_bzl_file_size`) and soft (`--soft_max_bzl_file_size`) file size thresholds for `.bzl` and `.scl` files in `BzlCompileFunction` using `StarlarkSemantics`. Checking the hard limit before reading file contents prevents catastrophic JVM heap exhaustion from oversized files, while the soft limit requires files exceeding the threshold to either be listed in the file specified by `--bzl_file_size_limit_allowlist` or explicitly opt out via a top-level `_KNOWN_OVERSIZED_BZL_FILE` variable.

Before:
```
ERROR: java.lang.OutOfMemoryError: Java heap space
```

After:
```
ERROR /workspace/pkg/foo.bzl: File '//pkg:foo.bzl' size (750000 bytes) exceeds the soft maximum size (500000 bytes). Split this file or move data out of Starlark. To opt out up to the hard limit, set `_KNOWN_OVERSIZED_BZL_FILE = "b/<bug_id>"` at the top level of the file.
```
PiperOrigin-RevId: 991638160
Change-Id: Ifcbe710d6d9c1f63564d4d333eabdf98b9b23d21