bazel: Rewrite a `/bin/bash` path on FreeBSD.
On FreeBSD, we attempt to invoke `:package_bazel_on_host_platform` in such a way
that we fail to execute:

```
ERROR: /home/jashankj/src/bazel-8.2.1/src/BUILD:265:9: Executing genrule //src:package-zip_nojdk failed: (Exit 127): bash failed: error executing Genrule command (from target //src:package-zip_nojdk)
  (cd /home/jashankj/src/bazel-8.2.1/work/tmp/bazel_yFViwhVU/out/execroot/_main && \
  exec env - \
    PATH=/home/jashankj/perl5/bin:/home/jashankj/bin:/home/jashankj/bin/freebsd-amd64:/home/jashankj/bin/local:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin://bin://sbin:/home/jashankj/.opam/4.11.0/bin:/home/jashankj/perl5/bin:/home/jashankj/.gem/ruby/current/bin \
  /usr/local/bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/freebsd-opt-exec-ST-fad1763555eb/bin/src/package-bazel-on-host-platform.sh bazel-out/freebsd-opt/bin/src/package_nojdk.zip  bazel-out/freebsd-opt/bin/src/embedded_tools_nojdk.zip bazel-out/freebsd-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar bazel-out/freebsd-opt/bin/src/install_base_key_nojdk bazel-out/freebsd-opt/bin/platforms-srcs.tar bazel-out/freebsd-opt/bin/src/main/java/net/starlark/java/eval/libcpu_profiler.so bazel-out/freebsd-opt/bin/src/main/tools/build-runfiles bazel-out/freebsd-opt/bin/src/main/tools/process-wrapper bazel-out/freebsd-opt/bin/src/main/tools/linux-sandbox bazel-out/freebsd-opt/bin/tools/osx/xcode-locator bazel-out/freebsd-opt/bin/src/main/tools/daemonize')
# Configuration: cb568ec60c768e46a7cb16574460fabadc83b6940b58976649d092736543cd9d
# Execution platform: //:default_host_platform
/usr/local/bin/bash: line 1: bazel-out/freebsd-opt-exec-ST-fad1763555eb/bin/src/package-bazel-on-host-platform.sh: cannot execute: required file not found
Target //src:bazel_nojdk failed to build
```

(Interestingly, we do the right thing for OpenBSD.)

PiperOrigin-RevId: 763676629
Change-Id: Ib7e07ce0a13c1459a249cbb82ddefc95ca8cb99f