Remove empty cc rule definitions
Since this commit 71ca0ed111ff3d842a0d23bc3a46bd2e6745491d the load
statements for these cc rules are required but the errors indicating
that were a bit strange:

Before:

```
ERROR: /private/tmp/foo/BUILD.bazel:7:8: //:bar: no such attribute 'srcs' in 'cc_test' rule
ERROR: /private/tmp/foo/BUILD.bazel:7:8: In rule 'bar', size '' is not a valid size.
ERROR: /private/tmp/foo/BUILD.bazel:7:8: In rule 'bar', timeout '' is not a valid timeout.
```

After:

```
ERROR: /private/tmp/foo/BUILD.bazel:7:1: name 'cc_test' is not defined
```