Automated rollback of commit 4594b7fd6c2516341cdd6e57f9eaaf22cf691f95.
*** Reason for rollback ***

It breaks examples/tutorial on ci.bazel.build [1] with error:

object of type 'Target' has no field 'objc'.

[1] http://ci.bazel.io/view/Dashboard/job/Tutorial/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/1023/console

*** Original change description ***

AppleBinary and AppleStaticLibrary no longer propagate unwrapped ObjcProvider.
This will prevent dependencies on apple_binary and apple_static_library from objc_library and other lower-level rules.

RELNOTES: None.
PiperOrigin-RevId: 162195726