Ignore usages of ignored flag aliases instead of failing
When a `.bazelrc` contains:
```
common --flag_alias=my_flag=//:my_flag
common --my_flag=value
```
commands that don't support Starlark flags no longer fails with:
```
ERROR: --my_flag=value :: Unrecognized option: --my_flag=value
```