Fixing issue with external j2objc protos
The output files are created without a repository, but the expected
filenames have them

This resolves issues when having a proto_library from an external build
file.

This seems to be a regression, so maybe should go into the 0.8.0 branch?

Note: Work at Square and we have a signed CLA with google

Note, without this fix we get errors like

```
ERROR: /private/var/tmp/_bazel_lewis/4a25cfc2b9b758043413ac58525ef6b4/external/AllProtos/BUILD.bazel:27:1: output 'external/AllProtos/squareup/objc/objc.j2objc.pb.m' was not created
ERROR: /private/var/tmp/_bazel_lewis/4a25cfc2b9b758043413ac58525ef6b4/external/AllProtos/BUILD.bazel:27:1: output 'external/AllProtos/squareup/objc/objc.j2objc.pb.h' was not created
```

Closes #4058.

PiperOrigin-RevId: 187480864