Fix DEFAULT_TOOLCHAIN_CONFIGURATION's reference to nonexistent condition.
The reference to `//src/conditions:openbsd` was invalid, and caused breakage:

```
ERROR: Analysis of target '//java/main:JavaBinary' failed; build aborted: no such package 'src/conditions': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
```