Use retrieved nestedSet for symlink planting
Prevent an NPE encountered when transitive packages are pruned before planting in BuildDriverFunction.

```
(13:13:58) FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'BuildDriverKey of ActionLookupKey: ConfiguredTargetKey{label=//autonomy/planning/corridor_map_generator:extended_corridor_location.orin, config=BuildConfigurationKey[eb69cd8e663e6b9c29ef248d6832d55cd81adb9501937e1bba8017d095e8d982]}' (requested by nodes )
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:550)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:414)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Null transitivePackagesForSymlinkPlanting
        at com.google.devtools.build.lib.skyframe.AutoValue_TopLevelStatusEvents_TopLevelTargetReadyForSymlinkPlanting.<init>(AutoValue_TopLevelStatusEvents_TopLevelTargetReadyForSymlinkPlanting.java:15)
        at com.google.devtools.build.lib.skyframe.TopLevelStatusEvents$TopLevelTargetReadyForSymlinkPlanting.create(TopLevelStatusEvents.java:72)
        at com.google.devtools.build.lib.skyframe.BuildDriverFunction.compute(BuildDriverFunction.java:230)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:461)
        ... 7 more
```

Closes #23400.

PiperOrigin-RevId: 666809249
Change-Id: Ibc257ec978d25273ea3e91e2cddeaba2fb19cd6d