Improve error messaing on invalid "--//foo:starlark_flag value" calls.
Bazel requires `--//foo:starlark_flag=value`. (i.e. equals as delimiter, not space).

Old error:
```
ERROR: --//foo:starlark_flag :: Expected value after --//foo:starlark_flag.
```

New error:
```
ERROR: --//foo:starlark_flag :: Expected value after --//foo:starlark_flag. Did you mean --//foo:starlark_flag=value?
````

Only adds the suggestion if the next arg exists and doesn't start with "-". So `--//foo:starlark_flag -c opt` won't trigger the suggestion.

PiperOrigin-RevId: 817820840
Change-Id: Idf291ca139e3772a93922d25b025daf4755210d2