Fix spitting out multiple "Build completed" messages.
Also make these a proper event, so that `--ui_event_filters` is applied
properly.

Fixes https://github.com/bazelbuild/bazel/issues/16085

RELNOTES[INC]:
This has the side effect of changing the message on unsuccessful builds from
```
FAILED: Build did NOT complete successfully (0 packages loaded)
```
to
```
ERROR: Build did NOT complete successfully
```
PiperOrigin-RevId: 484175656
Change-Id: I080ada6756734e5cdf236854101595949a57c083