Skip protobuf's test headers to fix bootstrap compile
Example of error otherwise:

ERROR: /tmp/bazel_GNfPxtiA/out/external/com_google_protobuf/BUILD.bazel:541:1: in cc_binary rule @com_google_protobuf//:protoc: cycle in dependency graph:
    //src:bazel
    //src:bazel-bin
    //src:package-zip
    //src:install_base_key
    //src:install_base_key-file
    //src:embedded_tools
    //src:embedded_tools_srcs
    //src/java_tools/junitrunner/java/com/google/testing/junit/runner:ExperimentalRunner_deploy.jar
    //src/java_tools/junitrunner/java/com/google/testing/junit/runner:ExperimentalRunner
    //src/java_tools/junitrunner/java/com/google/testing/junit/runner:experimental_test_runner
    //src/main/protobuf:worker_protocol_java_proto
    //src/main/protobuf:worker_protocol_proto
.-> @com_google_protobuf//:protoc (host)
|   @com_google_protobuf//:protoc_lib (host)
|   @com_google_protobuf//:protobuf (host)
|   @com_google_protobuf//:protobuf_lite (host)
|   @com_google_protobuf//:src/google/protobuf/compiler/cpp/cpp_test_bad_identifiers.pb.h (host)
|   @com_google_protobuf//:cc_test_protos_genproto (host)
|   @com_google_protobuf//:cc_wkt_protos_genproto (host)
`-- @com_google_protobuf//:protoc (host)
This cycle occurred because of a configuration option