Fix `//third_party:netty_tcnative` target on OpenBSD & FreeBSD.
On these platforms, no tcnative shared library is available.
Without this change, the build fails with the following error.

```
ERROR: /home/ad/tree/third_party/BUILD:612:8: in cmd attribute of genrule rule //third_party:filter_netty_dynamic_libs: variable '$<' : no input file

ERROR: /home/ad/tree/third_party/BUILD:612:8: Analysis of target '//third_party:filter_netty_dynamic_libs' failed
```

(The root cause was that the `:filter_netty_dynamic_libs` target
assumed it could copy the native library:
https://github.com/bazelbuild/bazel/blob/c418e9e2635a0afdcbb36f7c14b41fec8417a356/third_party/BUILD#L623
even when there was no native library:
https://github.com/bazelbuild/bazel/blob/c418e9e2635a0afdcbb36f7c14b41fec8417a356/third_party/BUILD#L620.)