Ninja integration: parse "pool" declarations and identifiers in rules
This adds a new parser to parse "pool" declarations and "pool" identifiers in Ninja rules, and adds them into NinjaScope. We currently don't do anything special with these yet, and are just doing enough so that we parse Ninja files correctly.

Without this, the following will fail:

```ninja
rule some_name
    pool = some_pool
    command = echo hello
```

```starlark
ninja_graph(
   name = "simple",
   main = "simple.ninja",
   ninja_srcs = [
       "simple.ninja",
   ],
   output_root = "out",
)
```

```
ERROR: in ninja_graph rule //:simple: Expected [IDENTIFIER], but got pool in fragment:
rule some_name
    pool = some_pool
    command = echo hello

ERROR: Analysis of target '//:simple' failed; build aborted: Analysis of target '//:simple' failed; build aborted
FAILED: Build did NOT complete successfully (6 packages loaded, 11 targets configured)
```

Closes #10868.

PiperOrigin-RevId: 298385134