[1/5] support C++20 Modules, add module_interfaces attr
I split the XXL PR https://github.com/bazelbuild/bazel/pull/19940 into several small patches.
This is the first patch of Support C++20 Modules, I add `module_interfaces` attr only

example

-  foo.cppm
```
// foo.cppm
export module foo;
// ...
```
- BUILD.bazel

```
cc_library(
    name="foo",
    copts=["-std=c++20"],
    module_interfaces=["foo.cppm"],
    # features=["cpp20_module"]
)

```

build failed with the following message

```
➜  bazel build :foo
ERROR: bazel_demo/BUILD.bazel:1:11: in cc_library rule //:foo:
Traceback (most recent call last):
        File "/virtual_builtins_bzl/common/cc/cc_library.bzl", line 40, column 42, in _cc_library_impl
        File "/virtual_builtins_bzl/common/cc/semantics.bzl", line 123, column 13, in _check_can_module_interfaces
Error in fail: attribute module_interfaces: requires --experimental_cpp20_modules
ERROR: bazel_demo/BUILD.bazel:1:11: Analysis of target '//:foo' failed
ERROR: Analysis of target '//:foo' failed; build aborted
INFO: Elapsed time: 0.106s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
```
To build with C++20 Modules, the flag `--experimental_cpp20_modules` must be added.

```
➜  bazel build :foo --experimental_cpp20_modules
ERROR: bazel_demo/BUILD.bazel:1:11: in cc_library rule //:foo:
Traceback (most recent call last):
        File "/virtual_builtins_bzl/common/cc/cc_library.bzl", line 41, column 34, in _cc_library_impl
        File "/virtual_builtins_bzl/common/cc/cc_helper.bzl", line 1225, column 13, in _check_cpp20_modules
Error in fail: to use C++20 Modules, the feature cpp20_modules must be enabled
ERROR: bazel_demo/BUILD.bazel:1:11: Analysis of target '//:foo' failed
ERROR: Analysis of target '//:foo' failed; build aborted
INFO: Elapsed time: 0.091s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
```

To build with C++20 Modules, the feature `cpp20_modules` must be enabled.

```
bazel build :foo --experimental_cpp20_modules --features cpp20_modules
```

the flag `--experimental_cpp20_modules` works on global and
the feature `cpp20_modules` work on each target

but in this patch, do nothing with C++20 Module Interfaces.

Closes #22425.

PiperOrigin-RevId: 643303029
Change-Id: I08d8a1186d2ddd1c632f1e768442e504b87a0691