Bump vanilla JDK from 11.0.1 to 11.0.2.
While testing Bazel with the upgraded embedded JDK we hit a bug which
was fixed by 11.0.2:
See
https://www.oracle.com/technetwork/java/javase/11-0-2-relnotes-5188746.html
for the release notes which lists
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8211883
as fixed.

The problem showed e.g. in our integration tests where we download
protobuf as external repository from github and we would show an
handshake error:
ERROR: [...]/BUILD:1:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf//:protoc', but this target could not be found because of: no such package '@com_google_protobuf//': java.io.IOException: Error downloading [https://github.com/google/protobuf/archive/7b28271a61a3da0a37f6fda399b0c4c86464e5b3.zip] to [...].zip: Received fatal alert: handshake_failure

Note that this commit does not the update of the embedded JDK yet.

Part of #6592.

RELNOTES: None

Closes #7335.

PiperOrigin-RevId: 232175766