Fix googletest target name
 I was following the tutorial and hit a wall here.
```
 bazel test //test:hello-test
ERROR: /home/eriff/.cache/bazel/_bazel_eriff/f6bb6ff4e6e38165bb9ceee09de6c8af/external/googletest+/BUILD.bazel: no such target '@@googletest+//:main': target 'main' not declared in package '' defined by /home/eriff/.cache/bazel/_bazel_eriff/f6bb6ff4e6e38165bb9ceee09de6c8af/external/googletest+/BUILD.bazel
ERROR: /home/eriff/repos/bazel-examples/cpp-tutorial/stage3/test/BUILD:1:8: no such target '@@googletest+//:main': target 'main' not declared in package '' defined by /home/eriff/.cache/bazel/_bazel_eriff/f6bb6ff4e6e38165bb9ceee09de6c8af/external/googletest+/BUILD.bazel and referenced by '//test:hello-test'
ERROR: Analysis of target '//test:hello-test' failed; build aborted: Analysis failed
```

Turns out the target name was wrong

Closes #24615.

PiperOrigin-RevId: 705084234
Change-Id: Id7359a9571cee79e36676e6ec53c8bfc45a4321d