Downgrade extraneous `use_repo` errror to a warning
If the root module's `MODULE.bazel` file contains
`use_repo(go_deps, "foobar")`, but the `go_deps` extension doesn't
generate a repository called `foobar`, a warning such as the following
will be shown when the `go_deps` extension is evaluated:

```
WARNING: <root>/MODULE.bazel:13:24: module extension "go_deps" from "@gazelle~override//:extensions.bzl" does not generate repository "foobar", yet it is imported as "foobar"
```

When the non-existent `foobar` repository is referenced, this still
results in an error:

```
ERROR: Skipping '@foobar//:bin': no such package '@gazelle~override~go_deps~foobar//': The repository '@gazelle~override~go_deps~foobar' could not be resolved: Repository '@gazelle~override~go_deps~foobar' is not defined
```

Previously, any evaluation of `go_deps` would have raised an error such
as:

```
ERROR: Analysis of target '//:gazelle' failed; build aborted: module extension "go_deps" from "@gazelle~override//:extensions.bzl" does not generate repository "foobar", yet it is imported as "foobar" in the usage at <root>/MODULE.bazel:13:24
```

This made it impossible to have tooling to fix `use_repo` calls run with
Bazel if that tooling in turn depends on the module extension it manages
`use_repo` calls for. It also seemed excessive to fail the build over
this as it is easily possible to continue as long as the extraneous repo
isn't referenced.

To prevent warning spam, warnings are only emitted for root module
usages.