Support LABEL_KEYED_STRING_DICT aspect attributes in query --output=proto.
Previously, `query --output=proto` errored out when an aspect defined an `attr.label_keyed_string_dict` attribute:
```
ERROR: Target "<target>", aspect attribute "<attr>": type "dict(label, string)" not yet supported with --output=proto.
```

This was introduced as a stopgap (b/149982967) to replace a fatal server crash when `AspectResolver` flattened all aspect dependencies and proto serialization could not distinguish per-aspect attributes. Because aspect dependencies are now tracked per aspect, we can serialize the attribute directly from its definition default value.

RELNOTES: Support `dict(label, string)` aspect attributes in `query --output=proto`.
PiperOrigin-RevId: 977785071
Change-Id: If015c49fd3f823dc4f5abae92c8063f0d50744fd