Generalize Label and RepositoryName getDisplayForm to accept non-main repository mappings.
`RepositoryName.getDisplayForm` strictly required the repository mapping to belong to the main repository, throwing `IllegalArgumentException` otherwise. This prevented `ToolchainContextUtil` from resolving apparent repository names when suggesting toolchain labels for rules defined in external repositories.

Generalizing `getDisplayForm` across `RepositoryName`, `PackageIdentifier`, and `Label` allows resolving apparent names in any context repository. In `ToolchainContextUtil`, suggested toolchains for rules in external repositories are now formatted using apparent labels visible in that rule's package rather than being omitted.

Before:
```
ERROR: Tried to set execution constraints for non-existent exec groups on @@rules_python+//pkg:my_rule: @rules_cc//cc:toolchain_type_2
```

After:
```
ERROR: Tried to set execution constraints for non-existent exec groups on @@rules_python+//pkg:my_rule: @rules_cc//cc:toolchain_type_2 (did you mean '@rules_cc//cc:toolchain_type_1'?)
```
PiperOrigin-RevId: 979787366
Change-Id: I0550b79dcdbe06dfc794d1ba862f49b94776116f