Prevent failures creating output directories
I would receive reports of build failures along these lines:

> ERROR: some/path/BUILD:156:32: Executing genrule //some/path:some_target failed: failed to create output directory '.../some/path/foo'

In order to root cause this, I made a minor change to Bazel to extend
its logging. See https://github.com/bazelbuild/bazel/pull/17951. With
that change applied, the error became:

> ERROR: some/path/BUILD:156:32: Executing genrule //some/path:some_target failed: failed to create output directory '.../some/path/foo': .../some/path/foo (Not a directory)

I was eventually able to reproduce this by manually creating an output
file at bazel-bin/some/path, followed by attempting to build the target.
It looks like Bazel simply attempts to create output directories without
taking into consideration whether a file already exists at the target
location. This is problematic when someone alters an existing build
target to emit a directory instead of a regular file.

Note that this only an issue when the remote action file system is used.
Plain builds (ones that don't use Builds without the Bytes or
bb_clientd) are unaffected. This change addresses this issue by reusing
the same fallback path creation strategy that plain builds already use.