Remove no longer available cmd option
```
ERROR: Query expressions involving 'buildfiles' or 'loadfiles' cannot be used with --output=location
```

Closes #4835.

PiperOrigin-RevId: 189888124