[8.8.0] Get the local and remote repo contents cache to work together (#29085)
* Also upload to the remote cache when the local cache is in use. The
fix is simple but subtle: the logic for the two caches in
`RepositoryFetchFunction` has to be flipped since the Skyframe restart
after adding an entry to the local cache meant that the same code path
would not be taken again.
* Fix a crash when using both by ensuring that the local repo contents
cache uses the file system backing the output base, not the workspace
directory:
```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@@rules_python+' (requested by nodes 'REPO_FILE:@@rules_python+')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:552)
Caused by: java.lang.IllegalArgumentException: Files are on different filesystems: .../external/@rules_python+.marker (on RemoteExternalOverlayFileSystem), .../.cache/bazel-repo/contents/_trash/... (on WindowsFileSystem)
	at com.google.devtools.build.lib.vfs.Path.checkSameFileSystem(Path.java:964)
	at com.google.devtools.build.lib.vfs.Path.renameTo(Path.java:630)
	at com.google.devtools.build.lib.vfs.FileSystemUtils.moveFile(FileSystemUtils.java:456)
	at com.google.devtools.build.lib.bazel.repository.cache.LocalRepoContentsCache.moveToCache(LocalRepoContentsCache.java:172)
```

Closes https://github.com/bazelbuild/bazel/pull/28002.

PiperOrigin-RevId: 855211557
Change-Id: I2f3c40a6aef594682fba989853f7ee982f30c294
(cherry picked from commit
https://github.com/bazelbuild/bazel/commit/b143070b825db7c968ee6e881959473693e17980)

Co-authored-by: Xdng Yng <wyverald@gmail.com>