bazel/native: In `unix_jni_bsd.cc`, use correct `struct stat` field name on FreeBSD.
When we switched from the `time_t`-typed slots to the `struct timeval`-typed
slots, we apparently missed one, and broke the build on FreeBSD:

```
ERROR: /home/jashankj/src/bazel-8.2.1/src/main/native/BUILD:75:10: Compiling src/main/native/unix_jni_bsd.cc failed: (Exit 1): clang failed: error executing CppCompile command (from target //src/main/native:libunix_jni.so)
  (cd /home/jashankj/src/bazel-8.2.1/work/tmp/bazel_zNq27xcM/out/execroot/_main && \
  exec env - \
    PATH=/home/jashankj/perl5/bin:/home/jashankj/bin:/home/jashankj/bin/freebsd-amd64:/home/jashankj/bin/local:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin://bin://sbin:/home/jashankj/.opam/4.11.0/bin:/home/jashankj/perl5/bin:/home/jashankj/.gem/ruby/current/bin \
    PWD=/proc/self/cwd \
  /usr/bin/clang -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++17' -MD -MF bazel-out/freebsd-opt/bin/src/main/native/_objs/libunix_jni.so/unix_jni_bsd.pic.d '-frandom-seed=bazel-out/freebsd-opt/bin/src/main/native/_objs/libunix_jni.so/unix_jni_bsd.pic.o' -fPIC -DBLAZE_OPENSOURCE -iquote . -iquote bazel-out/freebsd-opt/bin -iquote external/blake3+ -iquote bazel-out/freebsd-opt/bin/external/blake3+ -isystem src/main/native -isystem bazel-out/freebsd-opt/bin/src/main/native -isystem external/blake3+ -isystem bazel-out/freebsd-opt/bin/external/blake3+ '-std=c++17' -fPIC '-DBLAZE_JAVA_CPU=k8' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c src/main/native/unix_jni_bsd.cc -o bazel-out/freebsd-opt/bin/src/main/native/_objs/libunix_jni.so/unix_jni_bsd.pic.o)
# Configuration: cb568ec60c768e46a7cb16574460fabadc83b6940b58976649d092736543cd9d
# Execution platform: //:default_host_platform
src/main/native/unix_jni_bsd.cc:70:30: error: member reference base type 'const time_t' (aka 'const long') is not a structure or union
   70 |       return statbuf.st_mtime.tv_sec * 1000L +
      |              ~~~~~~~~~~~~~~~~^~~~~~~
1 error generated.
Target //src:bazel_nojdk failed to build
```

Fixes 4eba4a6204ae3106ce75327565f15e1aa57fe141 (https://github.com/bazelbuild/bazel/commit/4eba4a6204ae3106ce75327565f15e1aa57fe141).

PiperOrigin-RevId: 763726575
Change-Id: I90ba3035b4e2e277d33c0c5efb24ca34069fee92