When builds fail because select statements don't match, include in the error which conditions were checked.
In other words, go from:

ERROR: $WORKSPACE_ROOT/package/BUILD:69:12: Configurable attribute "srcs" doesn't match this configuration (would a default condition help?).

to:

ERROR: $WORKSPACE_ROOT/package/BUILD:69:12: Configurable attribute "srcs" doesn't match this configuration (would a default condition help?).
Conditions checked:
 //foo:condition1
 //foo:condition2

--
MOS_MIGRATED_REVID=99044040