Diagnose incompatible Java system classpaths
When the Java system classpath extracted from the target Java runtime
is more recent than the Java runtime used for Java compilation,
JavaBuilder now emits a `[BazelJavaConfiguration]` diagnostic with
actionable information instead of a bunch of "bad class file" errors
on `module-info` files.

Example:
```
error: [BazelJavaConfiguration] The Java 17 runtime used to run javac is not recent enough to compile for the Java 20 runtime in external/remotejdk20_linux. Either register a Java toolchain with a newer java_runtime or specify a lower --java_runtime_version.
```