Diagnose incompatible annotation processors
When an annotation processor is built targeting a language level that
isn't supported by the Java runtime used for compilation, JavaBuilder
now throws an exception with actionable information.

Example:
```
java.lang.IllegalArgumentException: The Java 17 runtime used to run javac is not recent enough to run the processor com.google.devtools.build.runfiles.AutoBazelRepositoryProcessor, which has been compiled targeting Java 20. Either register a Java toolchain with a newer java_runtime or, if this processor has been built with Bazel, specify a lower --tool_java_language_version.
	at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler.initProcessAnnotations(BlazeJavaCompiler.java:119)
        ...
```