Remove --extension_filter=all from bzlmod docs
`--extension_filter=all` is no longer valid, it seems to expect a list of labels for extensions. As far as I can tell, omitting the option includes all extensions anyway.
```sh
$ bazel mod graph --extension_info=usages --extension_filter=all
ERROR: While parsing option --extension_filter=all: Invalid argument all: missing .bzl label
```

Closes #27129.

PiperOrigin-RevId: 816384025
Change-Id: I80865bc3886b1843ff1c01a84785d2918c73a08e