Improve build summary to attribute failed top-level targets to failed dependency actions
When building multiple top-level targets (such as `bazel build //...`), `--show_result` (which defaults to `1`) previously suppressed `Target <label> failed to build` at the end of the build if the target threshold was exceeded.
Furthermore, when a top-level target failed due to an action in a dependency target (e.g. across a configuration transition), the summary did not attribute the failure to the dependency target.

Before:
```
$ bazel build //...
ERROR: ... GoCompilePkg hello_binary.a failed: ...
INFO: Elapsed time: 1.234s
FAILED: Build did NOT complete successfully
```
(Notice: No `Target //:broken_hello_filegroup failed to build` was printed in multi-target builds, and no dependency failure attribution was provided.)

After:
```
$ bazel build //...
ERROR: ... GoCompilePkg hello_binary.a failed: ...
Target //:broken_hello_filegroup failed to build
  due to action in //:hello_binary
INFO: Elapsed time: 1.234s
FAILED: Build did NOT complete successfully
```

This CL ensures failed top-level targets are always reported in the build summary and attributes them to the root cause dependency targets that produced the failed actions.

Fixes part of https://github.com/bazelbuild/bazel/issues/18139.

PiperOrigin-RevId: 969866895
Change-Id: Ia6c62041874b34e20abd6394ebd7764aebb43e4a