handle IOException in rename during CompactPersistentActionCache init
I've observed Bazel 9 failing as follows:

    ERROR: Couldn't create action cache: [unix_jni.cc:638] /tmp/.cache-bzlmod/bazel/_bazel_jenkins/output-base/action_cache -> /tmp/.cache-bzlmod/bazel/_bazel_jenkins/output-base/action_cache.bad (Invalid cross-device link). If error persists, use 'bazel clean'.

This unhandled IOException causes Bazel to fail to print the original
cause of the problem that drove it into `logAndThrowOrRecurse()`.

We here attempt to improve the reporting and allow Bazel to survive the problem.