Set --host_macos_minimum_os in .blazerc.
Following the advice in https://github.com/bazelbuild/bazel/issues/23116. Without this, I'm unable to build Bazel on my laptop because of errors like:

In file included from external/protobuf+/src/google/protobuf/json/internal/zero_copy_buffered_stream.cc:8:
bazel-out/darwin_arm64-opt-exec-ST-fad1763555eb/bin/external/protobuf+/src/google/protobuf/json/_virtual_includes/zero_copy_buffered_stream/google/protobuf/json/internal/zero_copy_buffered_stream.h:77:18: error: 'get<std::string, std::string, google::protobuf::json_internal::MaybeOwnedString::StreamOwned>' is unavailable: introduced in macOS 10.13
    return absl::get<std::string>(data_);
                 ^

PiperOrigin-RevId: 715284545
Change-Id: I2abd81280076e45655276fda82f2d3e451410dd0