Automated rollback of commit 2eac97e7720c8285843a55cbc307515c3a306905.
*** Reason for rollback ***

Roll forward after fixing known tools that rely on the old behavior. In general, tools should use the BEP instead of parsing stdout/stderr.

*** Original change description ***

Fix spitting out multiple "Build completed" messages.

Also make these a proper event, so that `--ui_event_filters` is applied
properly.

Fixes https://github.com/bazelbuild/bazel/issues/16085

RELNOTES[INC]:
This has the side effect of changing the message on unsuccessful builds from

```
FAILED: Build did NOT complete successfully (0 packages loaded)
```
to

```
ERROR: Build did NOT complete successfully
```
PiperOrigin-RevId: 496325379
Change-Id: I9b5b7ee7d77f7ac22e1031e7771e74ba966a043d