Set JAVA_HOME and PATH in src/test/shell/bin/bazel
This is an attempt to solve instances of the following error on macOS
and Windows:

```txt
==================== Test output for @other_repo//:test:
Error occurred during initialization of VM
java.lang.Error: Could not create SecurityManager
  at java.lang.System.initPhase3(java.base@11.0.15/System.java:2065)
Caused by: java.lang.ClassNotFoundException: allow
  at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@11.0.15/BuiltinClassLoader.java:581)
  at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@11.0.15/ClassLoaders.java:178)
  at java.lang.ClassLoader.loadClass(java.base@11.0.15/ClassLoader.java:522)
  at java.lang.Class.forName0(java.base@11.0.15/Native Method)
  at java.lang.Class.forName(java.base@11.0.15/Class.java:398)
  at java.lang.System.initPhase3(java.base@11.0.15/System.java:2050)
```

The same as commit 6462319a774422b1c93f7cd13b5736b342c8f3bc, the `bazel
test` command setting the correct runtime for the test script, but
passing the wrong JVM flags. The flags come from this expression in
`BazelJavaSemantics.getJvmFlags`:

```java
if (JavaRuntimeInfo.from(ruleContext).version() >= 17) {
  jvmFlags.add("-Djava.security.manager=allow");
}
```

Somehow, despite Bazel using the correct runtime to launch the target,
it's detecting the wrong runtime to determine which JVM flags to set.