docs : add `touch WORKSPACE`
It seems that we still need to touch a file named `WORKSPACE`
```
ERROR: The 'build' command is only supported from within a workspace.
```