EnvironmentalExecException: exit as LOCAL_ENVIRONMENTAL_ERROR
Based on an audit of all callers, I conclude that this exception is
primarily used to indicate a local system failure / misconfiguration,
e.g., inability to create an output directory due to missing
permissions.

PiperOrigin-RevId: 278370943